<?php
$names = array (
  'buy' => '采购清单',
  'contact' => '联系方式',
  'credit' => '荣誉资质',
  'footer' => '公共页脚',
  'header' => '公共页头',
  'index' => '公司首页',
  'introduce' => '公司介绍',
  'job' => '人才招聘',
  'link' => '友情链接',
  'main_contact' => '主栏联系方式',
  'main_credit' => '主栏荣誉资质',
  'main_elite' => '主栏产品推荐',
  'main_introduce' => '主栏公司介绍',
  'main_news' => '主栏公司新闻',
  'main_sell' => '主栏最新供应',
  'message' => '留言询价',
  'news' => '公司新闻',
  'sell' => '供应产品',
  'side' => '侧栏',
  'side_announce' => '侧栏网站公告',
  'side_contact' => '侧栏联系方式',
  'side_credit' => '侧栏荣誉资质',
  'side_link' => '侧栏友情链接',
  'side_news' => '侧栏新闻中心',
  'side_search' => '侧栏站内搜索',
  'side_type' => '侧栏产品分类',
);
?>